# Pakai mesin PHP 8.2 yang sudah ada Apache-nya
FROM php:8.2-apache

# Install ekstensi MySQLi supaya error tadi hilang
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Aktifkan mod_rewrite (berguna untuk .htaccess)
RUN a2enmod rewrite

# Copy semua file rental mobilmu ke folder publik server
COPY . /var/www/html/

# Atur port dinamis sesuai permintaan Railway
RUN sed -i 's/80/${PORT}/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
