# Menggunakan mesin PHP versi 8.2 yang sudah sepaket dengan web server Apache
FROM php:8.2-apache

# Menginstal ekstensi database agar fitur koneksi PHP native kamu berfungsi
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Mengaktifkan mod_rewrite (penting jika proyek kamu menggunakan file .htaccess)
RUN a2enmod rewrite

# Menyalin semua file rental_mobil_kita milikmu ke dalam folder publik Apache
COPY . /var/www/rental_mobil_kita

# Mengubah port default Apache agar cocok dengan sistem dinamis Railway
RUN sed -i 's/80/${PORT}/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf